COMBO_ENABLE = yes

# Breakout easter-egg game (OLED)
# Trigger: ESC + DEL held together on the GAME layer (2).
OPT_DEFS += -DBREAKOUT_ENABLE
OPT_DEFS += -DBREAKOUT_TRIGGER_LAYER=2
OPT_DEFS += -DBREAKOUT_TRIGGER_KEYCODE_1=KC_ESC
OPT_DEFS += -DBREAKOUT_TRIGGER_KEYCODE_2=KC_DEL
OPT_DEFS += -DBREAKOUT_RESTART_KEYCODE=KC_E
OPT_DEFS += -DBREAKOUT_KEY_LEFT=KC_S
OPT_DEFS += -DBREAKOUT_KEY_RIGHT=KC_F
OPT_DEFS += -DOLED_UPDATE_PROCESS_LIMIT=16

SRC += $(KEYMAP_PATH)/breakout.c
